"""Send internal brief email to sales team via SMTP.

All SMTP env vars are optional. If not configured the send is silently skipped
so the chat API never fails due to email issues.

Required env vars (all must be set for email to send):
    SMTP_HOST   e.g. smtp.gmail.com
    SMTP_USER   e.g. noreply@yourdomain.com
    SMTP_PASS   app password or SMTP credential
    SALES_EMAIL  recipient (default: sales@demo.steeldoorco.com)

Optional:
    SMTP_PORT   default 587 (STARTTLS)
    EMAIL_FROM  display address (defaults to SMTP_USER)
"""
from __future__ import annotations

import logging
import os
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .models import EnquiryRequest, QuoteResponse

logger = logging.getLogger(__name__)


def send_brief_email(
    *,
    brief: str,
    session_id: str,
    readiness_score: int,
    customer_name: str | None = None,
    routing: str | None = None,
) -> bool:
    """Email the internal brief to the sales team. Returns True on success."""
    smtp_host = os.environ.get("SMTP_HOST", "").strip()
    smtp_user = os.environ.get("SMTP_USER", "").strip()
    smtp_pass = os.environ.get("SMTP_PASS", "").strip()

    if not (smtp_host and smtp_user and smtp_pass):
        logger.debug("SMTP not configured — brief email skipped for %s", session_id)
        return False

    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    from_addr = os.environ.get("EMAIL_FROM", smtp_user).strip()
    sales_email = os.environ.get("SALES_EMAIL", "keejay1290@gmail.com").strip()

    name_part = customer_name or "Unknown"
    route_part = (routing or "sales").upper()
    subject = f"[AI Lead] {name_part} - Score {readiness_score}/100 -> {route_part} Team"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = sales_email

    plain = (
        f"New AI sales lead captured.\n\n"
        f"{brief}\n\n"
        f"---\n"
        f"Session ID: {session_id}\n"
        f"Auto-generated by Steel Door AI Consultant\n"
    )
    msg.attach(MIMEText(plain, "plain"))

    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
            server.ehlo()
            server.starttls(context=ctx)
            server.login(smtp_user, smtp_pass)
            server.sendmail(from_addr, [sales_email], msg.as_string())
        logger.info("Brief email sent for session %s", session_id)
        return True
    except Exception as exc:
        logger.warning("Brief email failed for session %s: %s", session_id, exc)
        return False


def send_enquiry_email(*, enquiry: "EnquiryRequest", reference: str) -> bool:
    """Notify sales team when a customer submits the enquiry form. Returns True on success."""
    smtp_host = os.environ.get("SMTP_HOST", "").strip()
    smtp_user = os.environ.get("SMTP_USER", "").strip()
    smtp_pass = os.environ.get("SMTP_PASS", "").strip()

    if not (smtp_host and smtp_user and smtp_pass):
        logger.debug("SMTP not configured — enquiry email skipped for %s", reference)
        return False

    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    from_addr = os.environ.get("EMAIL_FROM", smtp_user).strip()
    sales_email = os.environ.get("SALES_EMAIL", "keejay1290@gmail.com").strip()

    subject = f"[AI Enquiry] {enquiry.name} - {reference}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = sales_email

    plain = (
        f"New enquiry form submission.\n\n"
        f"Reference: {reference}\n"
        f"Name:      {enquiry.name}\n"
        f"Email:     {enquiry.email}\n"
        f"Phone:     {enquiry.phone or '-'}\n"
        f"Postcode:  {enquiry.postcode or '-'}\n"
        f"Message:   {enquiry.message or '-'}\n"
    )
    if enquiry.quote_reference:
        plain += f"\nLinked quote: {enquiry.quote_reference} (£{enquiry.quote_total or 0:,.2f})\n"
    plain += "\n---\nAuto-generated by Steel Door AI Consultant\n"
    msg.attach(MIMEText(plain, "plain"))

    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
            server.ehlo()
            server.starttls(context=ctx)
            server.login(smtp_user, smtp_pass)
            server.sendmail(from_addr, [sales_email], msg.as_string())
        logger.info("Enquiry email sent for %s", reference)
        return True
    except Exception as exc:
        logger.warning("Enquiry email failed for %s: %s", reference, exc)
        return False


def send_customer_quote_email(
    *,
    customer_email: str,
    customer_name: str | None,
    quote: "QuoteResponse",
) -> bool:
    """Send the quote summary to the customer's own email address. Returns True on success."""
    smtp_host = os.environ.get("SMTP_HOST", "").strip()
    smtp_user = os.environ.get("SMTP_USER", "").strip()
    smtp_pass = os.environ.get("SMTP_PASS", "").strip()

    if not (smtp_host and smtp_user and smtp_pass):
        logger.debug("SMTP not configured — customer quote email skipped for %s", quote.reference)
        return False

    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    from_addr = os.environ.get("EMAIL_FROM", smtp_user).strip()

    name_part = customer_name or "there"
    subject = f"Your Steel Door Estimate — {quote.reference}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = customer_email

    lines_txt = "\n".join(f"  {ln.label}: £{ln.amount:,.2f}" for ln in quote.lines)
    if quote.sale_discount:
        lines_txt += f"\n  Summer Sale discount: -£{quote.sale_discount:,.2f}"

    plain = (
        f"Hi {name_part},\n\n"
        f"Thanks for chatting with the Steel Door Company AI consultant. "
        f"Here's your indicative estimate:\n\n"
        f"Reference: {quote.reference}\n"
        f"Product:   {quote.product_name}\n"
        f"Quantity:  {quote.quantity}\n\n"
        f"Price breakdown:\n{lines_txt}\n\n"
        f"  Subtotal (exc. VAT): £{quote.subtotal:,.2f}\n"
        f"  VAT (20%):           £{quote.vat:,.2f}\n"
        f"  TOTAL INC. VAT:      £{quote.total:,.2f}\n\n"
        f"Lead time: {quote.lead_time}\n\n"
        f"This is an indicative estimate only, subject to a free site survey. "
        f"A member of our team will be in touch shortly to confirm and arrange your survey.\n\n"
        f"For anything urgent:\n"
        f"  Phone: 01785 526016\n"
        f"  Email: sales@steeldoorcompany.co.uk\n"
        f"  Mon-Fri 8am-6pm | Sat 9am-2pm\n\n"
        f"Kind regards,\nSteel Door Company\nUnit C, Scarlet Court, Stafford ST16 1YJ\n"
        f"---\nAuto-generated by Steel Door AI Consultant\n"
    )
    msg.attach(MIMEText(plain, "plain"))

    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
            server.ehlo()
            server.starttls(context=ctx)
            server.login(smtp_user, smtp_pass)
            server.sendmail(from_addr, [customer_email], msg.as_string())
        logger.info("Customer quote email sent for %s", quote.reference)
        return True
    except Exception as exc:
        logger.warning("Customer quote email failed for %s: %s", quote.reference, exc)
        return False
