"""Send internal brief email to sales team via SMTP.

All SMTP env vars are optional. If not configured the send is silently skipped
so the chat API never fails due to email issues.

Required env vars (all must be set for email to send):
    SMTP_HOST   e.g. smtp.gmail.com
    SMTP_USER   e.g. noreply@yourdomain.com
    SMTP_PASS   app password or SMTP credential
    SALES_EMAIL  recipient (default: sales@demo.steeldoorco.com)

Optional:
    SMTP_PORT   default 587 (STARTTLS)
    EMAIL_FROM  display address (defaults to SMTP_USER)
"""
from __future__ import annotations

import logging
import os
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .models import EnquiryRequest

logger = logging.getLogger(__name__)


def send_brief_email(
    *,
    brief: str,
    session_id: str,
    readiness_score: int,
    customer_name: str | None = None,
    routing: str | None = None,
) -> bool:
    """Email the internal brief to the sales team. Returns True on success."""
    smtp_host = os.environ.get("SMTP_HOST", "").strip()
    smtp_user = os.environ.get("SMTP_USER", "").strip()
    smtp_pass = os.environ.get("SMTP_PASS", "").strip()

    if not (smtp_host and smtp_user and smtp_pass):
        logger.debug("SMTP not configured — brief email skipped for %s", session_id)
        return False

    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    from_addr = os.environ.get("EMAIL_FROM", smtp_user).strip()
    sales_email = os.environ.get("SALES_EMAIL", "sales@demo.steeldoorco.com").strip()

    name_part = customer_name or "Unknown"
    route_part = (routing or "sales").upper()
    subject = f"[AI Lead] {name_part} - Score {readiness_score}/100 -> {route_part} Team"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = sales_email

    plain = (
        f"New AI sales lead captured.\n\n"
        f"{brief}\n\n"
        f"---\n"
        f"Session ID: {session_id}\n"
        f"Auto-generated by Steel Door AI Consultant\n"
    )
    msg.attach(MIMEText(plain, "plain"))

    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
            server.ehlo()
            server.starttls(context=ctx)
            server.login(smtp_user, smtp_pass)
            server.sendmail(from_addr, [sales_email], msg.as_string())
        logger.info("Brief email sent for session %s to %s", session_id, sales_email)
        return True
    except Exception as exc:
        logger.warning("Brief email failed for session %s: %s", session_id, exc)
        return False


def send_enquiry_email(*, enquiry: "EnquiryRequest", reference: str) -> bool:
    """Notify sales team when a customer submits the enquiry form. Returns True on success."""
    smtp_host = os.environ.get("SMTP_HOST", "").strip()
    smtp_user = os.environ.get("SMTP_USER", "").strip()
    smtp_pass = os.environ.get("SMTP_PASS", "").strip()

    if not (smtp_host and smtp_user and smtp_pass):
        logger.debug("SMTP not configured — enquiry email skipped for %s", reference)
        return False

    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    from_addr = os.environ.get("EMAIL_FROM", smtp_user).strip()
    sales_email = os.environ.get("SALES_EMAIL", "sales@demo.steeldoorco.com").strip()

    subject = f"[AI Enquiry] {enquiry.name} - {reference}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = sales_email

    plain = (
        f"New enquiry form submission.\n\n"
        f"Reference: {reference}\n"
        f"Name:      {enquiry.name}\n"
        f"Email:     {enquiry.email}\n"
        f"Phone:     {enquiry.phone or '-'}\n"
        f"Postcode:  {enquiry.postcode or '-'}\n"
        f"Message:   {enquiry.message or '-'}\n"
    )
    if enquiry.quote_reference:
        plain += f"\nLinked quote: {enquiry.quote_reference} (£{enquiry.quote_total or 0:,.2f})\n"
    plain += "\n---\nAuto-generated by Steel Door AI Consultant\n"
    msg.attach(MIMEText(plain, "plain"))

    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
            server.ehlo()
            server.starttls(context=ctx)
            server.login(smtp_user, smtp_pass)
            server.sendmail(from_addr, [sales_email], msg.as_string())
        logger.info("Enquiry email sent for %s to %s", reference, sales_email)
        return True
    except Exception as exc:
        logger.warning("Enquiry email failed for %s: %s", reference, exc)
        return False
